name: Deploy to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: deploy on docker hub
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
          VERSION=php-7.2
          docker login --username jacobsamro --password ${{secrets.DOCKER_HUB_SECRET}}
          docker build . -t jacobsamro/larahp:$VERSION
          docker push jacobsamro/larahp:$VERSION
        env:
          CI: true
